services:
  node1:
    build: .
    container_name: dbdb_node1
    restart: unless-stopped
    ports:
      - "8221:8221"
      - "2221:2221"
    volumes:
      - dbdb-data-1:/app/data
    command: --node-id node1 --raft-port 2221 --http-port 8221 --bootstrap
    networks:
      - dbdb-net
    hostname: node1

  node2:
    build: .
    container_name: dbdb_node2
    restart: unless-stopped
    ports:
      - "8222:8222"
      - "2222:2222"
    volumes:
      - dbdb-data-2:/app/data
    command: --node-id node2 --raft-port 2222 --http-port 8222 --join node1:8221
    networks:
      - dbdb-net
    hostname: node2
    depends_on:
      - node1

  node3:
    build: .
    container_name: dbdb_node3
    restart: unless-stopped
    ports:
      - "8223:8223"
      - "2223:2223"
    volumes:
      - dbdb-data-3:/app/data
    command: --node-id node3 --raft-port 2223 --http-port 8223 --join node1:8221
    networks:
      - dbdb-net
    hostname: node3
    depends_on:
      - node1

networks:
  dbdb-net:
    driver: bridge

volumes:
  dbdb-data-1:
  dbdb-data-2:
  dbdb-data-3: